// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGerencialAcademia.Data.Context;

namespace SistemaGerencialAcademia.Data.Migrations
{
    [DbContext(typeof(AcademiaDbContext))]
    [Migration("20200613225233_CriarBancoETabelas")]
    partial class CriarBancoETabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaGerencialAcademia.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Identidade")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<long>("NumeroDeMatricula")
                        .HasColumnType("bigint");

                    b.Property<int>("PlanoDePagamento")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaAvaliacaoFisica")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("VencimentoPagamento")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemaGerencialAcademia.Dominio.Entidades.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("SistemaGerencialAcademia.Dominio.Entidades.InformacoesPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("InformacoesDePagamento");
                });

            modelBuilder.Entity("SistemaGerencialAcademia.Dominio.Entidades.PeriodoDeFerias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("PeriodosDeFerias");
                });

            modelBuilder.Entity("SistemaGerencialAcademia.Dominio.Entidades.Endereco", b =>
                {
                    b.HasOne("SistemaGerencialAcademia.Dominio.Entidades.Cliente", "Cliente")
                        .WithOne("Endereco")
                        .HasForeignKey("SistemaGerencialAcademia.Dominio.Entidades.Endereco", "ClienteId")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGerencialAcademia.Dominio.Entidades.InformacoesPagamento", b =>
                {
                    b.HasOne("SistemaGerencialAcademia.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany("InformacoesPagamentos")
                        .HasForeignKey("ClienteId")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaGerencialAcademia.Dominio.Entidades.PeriodoDeFerias", b =>
                {
                    b.HasOne("SistemaGerencialAcademia.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany("PeriodosDeFerias")
                        .HasForeignKey("ClientId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
